server:
  port: 5000

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials RETAIN_FIRST
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_URL:http://localhost:5001}
          predicates:
            - Path=/api/auth/**
          filters:
            - JwtAuthenticationFilter

        - id: movie-service
          uri: ${MOVIE_SERVICE_URL:http://localhost:5002}
          predicates:
            - Path=/api/movies/**
          filters:
            - JwtAuthenticationFilter

        - id: review-service
          uri: ${REVIEW_SERVICE_URL:http://localhost:5003}
          predicates:
            - Path=/api/reviews/**
          filters:
            - JwtAuthenticationFilter
