server.port=5003
spring.application.name=review-service

# MongoDB Configuration
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:${SPRING_DATA_MONGODB_URL:${MONGODB_URI:${MONGO_URI:mongodb://localhost:27017/reviewdb}}}}
